id: 2998e1821f104a24a96baf726b20400f
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_157-The_Questions_of_the_Kimnara_King_Druma-v2
  language: bo
  author: ''
  volume: {}
